# SPDX-License-Identifier: GPL-2.0
#
# Makefile for common V4L/DVB tuners
#

ccflags-y += -I$(M)/frontends


# Please keep it alphabetically sorted by Kconfig name
# (e. g. LC_ALL=C sort Makefile)
tda18271-objs := tda18271-maps.o tda18271-common.o tda18271-fe.o
obj-$(CONFIG_MEDIA_TUNER_TDA18271) += tda18271.o
obj-$(CONFIG_MEDIA_TUNER_TDA8290) += tda8290.o
obj-$(CONFIG_MEDIA_TUNER_TDA827X) += tda827x.o
obj-$(CONFIG_MEDIA_TUNER_XC5000) += xc5000.o
obj-$(CONFIG_MEDIA_TUNER_M88RS6000T) += m88rs6000t.o
obj-$(CONFIG_MEDIA_TUNER_SI2157) += si2157.o
obj-$(CONFIG_MEDIA_TUNER_TDA18212) += tda18212.o
obj-$(CONFIG_MEDIA_TUNER_AV201X) += av201x.o
obj-$(CONFIG_MEDIA_TUNER_STV6120) += stv6120.o
obj-$(CONFIG_MEDIA_TUNER_R848) += r848.o
obj-$(CONFIG_MEDIA_TUNER_MXL603) += mxl603.o
obj-$(CONFIG_MEDIA_TUNER_RDA5816) += rda5816.o
obj-$(CONFIG_MEDIA_TUNER_R850) += r850.o
